{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sweidnumbr
  version: {{ version|replace("-", "_") }}

source:
  fn: sweidnumbr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sweidnumbr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sweidnumbr/sweidnumbr_{{ version }}.tar.gz
  sha256: 30175db3a1f7759fff9021955c3da1ca742d88c24a9ca5972f2b71601adff27f

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lubridate >=1.4
    - r-stringr
  run:
    - r-base
    - r-lubridate >=1.4
    - r-stringr

test:
  commands:
    - $R -e "library('sweidnumbr')"           # [not win]
    - "\"%R%\" -e \"library('sweidnumbr')\""  # [win]

about:
  home: https://github.com/rOpenGov/sweidnumbr/
  license: BSD_2_clause
  license_file: LICENSE
  summary: Structural handling of identity numbers used in the Swedish administration such as personal identity numbers ('personnummer') and organizational identity
    numbers ('organisationsnummer').
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
