{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sweidnumbr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sweidnumbr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sweidnumbr/sweidnumbr_{{ version }}.tar.gz
  sha256: 174b6d0ffa43d08febebf2e8d7cf4eefed8e057bf479594e0b91f30b7932f870

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-lubridate >=1.5
    - r-stringr
  run:
    - r-base
    - r-checkmate
    - r-lubridate >=1.5
    - r-stringr

test:
  commands:
    - $R -e "library('sweidnumbr')"           # [not win]
    - "\"%R%\" -e \"library('sweidnumbr')\""  # [win]

about:
  home: https://github.com/rOpenGov/sweidnumbr/
  license: BSD-2-Clause
  summary: Structural handling of identity numbers used in the Swedish administration such as personal identity numbers ('personnummer') and organizational identity numbers ('organisationsnummer').
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sweidnumbr
# Type: Package
# Title: Handling of Swedish Identity Numbers
# Version: 1.4.2
# Date: 2020-03-21
# Author: Mans Magnusson and Erik Bulow
# Maintainer: Mans Magnusson <mons.magnusson@gmail.com>
# Description: Structural handling of identity numbers used in the Swedish administration such as personal identity numbers ('personnummer') and organizational identity numbers ('organisationsnummer').
# VignetteBuilder: rmarkdown, knitr
# URL: https://github.com/rOpenGov/sweidnumbr/
# BugReports: https://github.com/rOpenGov/sweidnumbr/issues
# License: BSD_2_clause + file LICENSE
# Depends: R (>= 3.2)
# Encoding: UTF-8
# Imports: lubridate (>= 1.5), stringr, checkmate
# Suggests: testthat (>= 1.0.0), rmarkdown, knitr
# LazyData: true
# RoxygenNote: 7.0.1
# NeedsCompilation: no
# Packaged: 2020-03-29 15:25:03 UTC; mansmagnusson
# Repository: CRAN
# Date/Publication: 2020-03-29 15:50:02 UTC
