appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Rodlrm5/uQzFmduVqUnG41k1JrDqlLEhpkp7XhuGbzfHCRmJU9eyqMLizYdJCBdhRusBdfZVPfzNn9nCor8YMue//vKbcxh1rY3nI8CyNseMBhIpxjwtWURgqRHIaqnYtXhqDlaWFHhJL7kWEXtHyO4/ob9EK9zWoZ1bAQnSfSgAGhKVgRut960g0JgZAeODeQYbdKSvzlO0HJm7vNt6v+noUho8dCDcqp/OvsRqQORlMDPpOe9z7YDzC9zMQ4wAgkZhMcF/9k/0fuLUi3bOFW5FS6reRsDSH45ueD4Ko2YAZnAKnkUZ8nKeKkIiXt6UOAJE8rjpwDfQ3QrI4iHAf7m4yt1gaa/qPpQVfg8/X9Nq57fMBAqsyBBfxTsmCeFFy05X/nX5zKF3uqnVHbmVVs3yoy1SfRa7FWJBxr2YWSAHEfqu7fHkSzmQwyGlu6wDeM3dSLakRJmqARQWw3nm2cbMifuxL0rq4lJMW13Ai9ApOxIAizYo43nLlTYjtgElfpXkhW9urQt5ZQSXEfV8P5NXytWeDrcHj2X4AybQNVtc2H7Ch+l4/VJK8o3yLc13Ohv1jYUPx7aoETTLHkeel4mp3GVbVsuQXWk3kI4Bl/L6ExTpLjhRsP+uD47zeQ7Qzoahw4g35pLyyW+aAABoaonK4WqDpUBO5D7cnq2bmOI=}
